In [11]:
import pandas as pd

df = pd.read_csv("cleaned_dataset/tracks.csv")

df.head()

,track_id,track_name,album_id,genre_id,popularity,duration_ms,explicit
0,5SuOikwiRyPMVoIQDJUgSV,Comedy,1,1,73,230666,False
1,4qPNDBW1i3p13qLCt0Ki3A,Ghost - Acoustic,2,1,55,149610,False
2,1iJBSr7s7jYXzM8EGcbK5b,To Begin Again,3,1,57,210826,False
3,6lfxq3CG4xtTiEg7opyCyx,Can't Help Falling In Love,4,1,71,201933,False
4,5vjLSffimiIP26QG5WcN2K,Hold On,5,1,82,198853,False

In [12]:
df['explicit'] = df['explicit'].map({
    True: 1,
    False: 0,
    'True': 1,
    'False': 0
})

df['explicit'].value_counts()

explicit
0    103832
1      9718
Name: count, dtype: int64

In [13]:
duplicates = df[df.duplicated(subset=['track_id'], keep=False)]

duplicates

,track_id,track_name,album_id,genre_id,popularity,duration_ms,explicit
0,5SuOikwiRyPMVoIQDJUgSV,Comedy,1,1,73,230666,0
1,4qPNDBW1i3p13qLCt0Ki3A,Ghost - Acoustic,2,1,55,149610,0
5,01MVOl9KtVTNfFiBU9I7dc,Days I Will Remember,6,1,58,214240,0
6,6Vc5wAMmXdKIAM7WUoEb7N,Say Something,7,1,74,229400,0
7,1EzrEOXmMH3G43AXT1y7pA,I'm Yours,8,1,80,242946,0
...,...,...,...,...,...,...,...
113122,1saXUvvFlAQaefZUFVmhCn,Jesus We Love You - Live,1966,114,53,415079,0
113155,1Q5jFp1g2Ns4gBsHRpcqhu,In The Ordinary - Spontaneous,575,114,50,174971,0
113167,71dLJx3qHOTQMTvvoE2dmd,King of My Heart,1934,114,48,330840,0
113169,6OG5TBCmuTOuWCzSGsETrE,Simple,575,114,48,351236,0
113191,7xsirhcgFWOnItsGuBfrv9,Closer,2184,114,49,413573,0

In [15]:
df = df.drop_duplicates(subset=['track_id'])

In [16]:
df.dtypes

track_id         str
track_name       str
album_id       int64
genre_id       int64
popularity     int64
duration_ms    int64
explicit       int64
dtype: object

In [20]:
df.to_csv("tracks_clean.csv", index=False)